tickers:
  tickers_list_filename: 'sp500_tickers_list'
  tickers_list_save_path: './metadata/tickers_list/'
  tickers_wikipedia_url: 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
  exclude_tickers:
    - GOOG

stock:
  stock_data_start_date: '2010-01-01'
  stock_data_save_path: './data/raw_stocks/'
  stock_data_processed_save_path: './data/processed_data/'


configs:
  train_config: './configs/train/train_cfg.yaml'
  eval_config: './configs/evaluation/eval_cfg.yaml'
  deploy_config: './configs/deployment/deployment_cfg.yaml'