# Name of the workflow
name: Run Tests

# When to run the workflow
on:
  # When there is a push
  push:
    # To main
    branches: [main]

  # When a pull request is created
  pull_request:

    # That targets the main branch
    branches: [main]

jobs:
  ci:
    # Runs on ubuntu
    runs-on: ubuntu-latest

    steps:

      # First get the repo
      - name: Check out repo
        uses: actions/checkout@v3

      # Setup the docker action for building
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build the airflow docker image, give it a name
      # Look for the Dockerfile.airflow file in the root
      - name: Build Airflow Docker Image
        run: |
          docker build -t dev-image -f Dockerfile.dev .

      # --rm means remove the container after it finishes running
      # -v Mount the entire repo into the container at /app
      # -w Set the working directory inside the container
      # Run pytest 
      - name: Run tests inside Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/opt/airflow -w /opt/airflow dev-image pytest tests/
